# Generated by Django 2.2 on 2022-07-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='userRoom',
        ),
    ]
