# Generated by Django 2.2 on 2022-07-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220729_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='plan',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Plan'),
        ),
    ]
