# Generated by Django 2.2 on 2022-08-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220731_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='plan',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Plan'),
        ),
    ]
