# Generated by Django 2.2 on 2022-08-04 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20220803_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 16, 35, 533970, tzinfo=utc)),
        ),
    ]
