# Generated by Django 2.2 on 2022-08-10 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20220809_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='userRoom',
        ),
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 8, 1, 46, 270941, tzinfo=utc)),
        ),
    ]
