# Generated by Django 2.2 on 2022-06-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='postUser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='postUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
