# Generated by Django 2.2 on 2022-07-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfIntro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='language_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
