# Generated by Django 2.2 on 2022-07-12 12:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220704_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=app.models.upload_img_path),
        ),
    ]
