# Generated by Django 2.2 on 2022-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='selfIntro',
            field=models.CharField(default='', max_length=100),
        ),
    ]
