# Generated by Django 2.2 on 2022-07-19 04:16

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220714_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('language_category', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=app.models.upload_project_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userPlan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
    ]
