# Generated by Django 2.2 on 2022-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220719_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='repository_url',
            field=models.URLField(default=''),
        ),
    ]
