# Generated by Django 2.2 on 2022-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_plan_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfIntro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
