# Generated by Django 2.2 on 2022-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220720_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='repository_url',
            field=models.URLField(default='', null=True),
        ),
    ]
