# Generated by Django 2.2 on 2022-07-28 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220723_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 6, 15, 15, 838153, tzinfo=utc)),
        ),
    ]
