# Generated by Django 2.2 on 2022-07-28 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220728_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 16, 20, 33, 590728, tzinfo=utc)),
        ),
    ]
