# Generated by Django 2.2 on 2022-07-29 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220729_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 14, 15, 50, 124803, tzinfo=utc)),
        ),
    ]
