# Generated by Django 2.2 on 2022-07-31 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220729_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 5, 15, 54, 155854, tzinfo=utc)),
        ),
    ]
