# Generated by Django 2.2 on 2022-08-01 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220731_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 0, 54, 49, 97507, tzinfo=utc)),
        ),
    ]
