# Generated by Django 2.2 on 2022-08-01 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220801_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 14, 20, 19, 661632, tzinfo=utc)),
        ),
    ]
