# Generated by Django 2.2 on 2022-08-03 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220801_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 9, 25, 11, 472869, tzinfo=utc)),
        ),
    ]
