# Generated by Django 2.2 on 2022-08-09 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220804_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 9, 43, 19, 107988, tzinfo=utc)),
        ),
    ]
